name: biocom2
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  curved_navigation_bar: ^0.3.2
  humanitarian_icons: ^0.1.0
  flutter_screenutil: ^0.4.2
  animated_text_kit: ^2.0.0
  simple_animations: ^1.1.3
  page_transition: ^1.1.4
  ff_navigation_bar: ^0.1.5
  custom_navigation_bar: ^0.2.6
  flutter_icons: ^1.1.0
  slide_popup_dialog: ^0.0.2
  google_maps_flutter: ^0.5.27+2
  fab_circular_menu: ^1.0.0
  permission: ^0.1.7
  google_map_polyline:
  html: ^0.14.0+3
  flutter_svg: ^0.17.4
  geolocator: ^3.0.1
  modal_progress_hud: ^0.1.3
  snack: ^1.0.4
  geocoder: ^0.2.1
  location:
  carousel_slider:
  gradient_app_bar: ^0.1.3
  draw_graph: ^0.0.1
  http:
  flutter_html: ^1.0.0
  qr_code_scanner: ^0.0.13
  time_range_picker: ^1.0.2
  multiselect_formfield: ^0.1.3
  step_progress_indicator: ^0.2.3+6
  syncfusion_flutter_barcodes: ^18.2.44-beta
  amazon_cognito_identity_dart_2: ^0.1.14
  platform_alert_dialog: ^1.0.0+2
  searchable_dropdown: ^1.1.3
  rflutter_alert: ^1.0.3
  shared_preferences: ^0.5.8
  localstorage: ^3.0.2+5
  hive: ^1.4.1+1
  hive_flutter: ^0.2.1
  path_provider: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/one.png
    - assets/image_01.png
    - assets/image_02.png
    - assets/doctor_vectors/
    - assets/doctor_nobg/
    - assets/images/
    - assets/icons/
    fonts:
      - family: Pacifico
        fonts:
          - asset: fonts/Pacifico-Regular.ttf
      - family: FredokaOne
        fonts:
          - asset: fonts/FredokaOne-Regular.ttf
      - family: Jost
        fonts:
          - asset: fonts/Jost-Regular.ttf
      - family: Merriweather
        fonts:
          - asset: fonts/Merriweather-Regular.ttf
      - family: Nunito
        fonts:
          - asset: fonts/Nunito-Regular.ttf
      - family: CustomIcons
        fonts:
          - asset: assets/CustomIcons.ttf
      - family: Poppins
        fonts:
          - asset: assets/Poppins-Regular.ttf
      - family: Montserrat
        fonts:
          - asset: assets/Montserrat-Regular.ttf
          - asset: assets/Montserrat-Bold.ttf
          - asset: assets/Montserrat-Medium.ttf
      - family: Poppins-Medium
        fonts:
          - asset: assets/Poppins-Medium.ttf
      - family: AbrilFatface
        fonts:
          - asset: assets/AbrilFatface-Regular.ttf

#     - family: Schyler
#       fonts:
#         - asset: fonts/Schyler-Regular.ttf
#         - asset: fonts/Schyler-Italic.ttf
#           style: italic
#     - family: Trajan Pro
#       fonts:
#         - asset: fonts/TrajanPro.ttf
#         - asset: fonts/TrajanPro_Bold.ttf
#           weight: 700